# Generated by Django 5.0.14 on 2026-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_purge_stale_pending_signups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingsignup',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Legacy Stripe flag — row is removed once the user verifies OTP or completes checkout.'),
        ),
    ]
