# Generated by Django 5.0.14 on 2026-07-27 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_refundapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundapplication',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Admin notes'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Notify email sent'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='member_email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Applicant email'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='member_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Applicant name'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='message',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='program_label',
            field=models.CharField(max_length=200, verbose_name='Purchase / program'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='purchase_key',
            field=models.CharField(blank=True, max_length=120, verbose_name='Purchase key'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='purchases_summary',
            field=models.TextField(blank=True, verbose_name='All paid purchases'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='request_type',
            field=models.CharField(choices=[('Founder Audit', 'Founder Audit'), ('Full Refund', 'Full Refund'), ('Full Replacement', 'Full Replacement'), ('Replacement Program', 'Full Replacement (legacy)')], db_index=True, default='Full Refund', max_length=80, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20, verbose_name='Review status'),
        ),
        migrations.AlterField(
            model_name='refundapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_applications', to=settings.AUTH_USER_MODEL, verbose_name='Linked account'),
        ),
    ]
