# Generated by Django 5.2.13 on 2026-05-12 05:27

import apps.video_streaming.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0014_backfill_transcode_progress_for_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamvideo',
            name='hls_path',
            field=models.URLField(blank=True, default='', help_text='Legacy field from the old HLS pipeline; unused. Left blank for new uploads.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='streamvideo',
            name='original_video',
            field=models.FileField(blank=True, help_text='Original MP4 (or other supported format). Stored privately; served only via signed playback URLs.', upload_to=apps.video_streaming.models.stream_video_original_upload_to),
        ),
        migrations.AlterField(
            model_name='streamvideo',
            name='transcode_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Upload / pipeline status. Ready means original file is stored and can be played.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
