# Generated by Django 5.0.14 on 2026-05-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0015_streamvideo_signed_mp4_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplaylistpurchase',
            name='currency',
            field=models.CharField(default='usd', max_length=12),
        ),
    ]
