# Generated by Django 5.0.14 on 2026-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0027_level1_and_vault_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplaylist',
            name='category',
            field=models.CharField(choices=[('business_model', 'Business Model'), ('business_psychology', 'Business Behaviour Psychology')], db_index=True, default='business_psychology', help_text='Programs grouping used by dashboard filters.', max_length=32),
        ),
    ]
