# Generated by Django 5.0.14 on 2026-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0030_business_model_program_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplaylist',
            name='vault_plan_slug',
            field=models.CharField(blank=True, db_index=True, help_text='Optional vault checkout slug: full pack (agentic_ai) or module (agentic_ai_c01, trading_scalpel_protocol). Links this playlist to mid-ticket pack modules for unlock + Open from the vault modal.', max_length=48),
        ),
    ]
