# Generated by Django 5.0.14 on 2026-07-01 06:09

import apps.video_streaming.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0031_alter_streamplaylist_vault_plan_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlaylistAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Member-facing label (e.g. Course workbook, Cheat sheet PDF).', max_length=255)),
                ('file', models.FileField(help_text='PDF, DOCX, XLSX, ZIP, or other reference file for this playlist.', upload_to=apps.video_streaming.models.stream_playlist_attachment_upload_to)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='video_streaming.streamplaylist')),
            ],
            options={
                'ordering': ['playlist', 'order', 'id'],
            },
        ),
    ]
