# Generated by Django 5.2.13 on 2026-05-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_tracking', '0006_affiliatewithdrawalaccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='affiliate_t_profile_b2965f_idx',
            old_name='affiliate_tr_profile_425e0f_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='affiliate_t_section_acf6db_idx',
            old_name='affiliate_tr_section_d2ae49_idx',
        ),
    ]
