# Generated by Django 5.2.13 on 2026-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_tracking', '0010_withdrawalrequest_transferred_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionreferral',
            name='section',
            field=models.CharField(choices=[('complete', 'Complete Programs Affiliate'), ('single', 'Single Program'), ('pawn', 'The Pawn'), ('king', 'The Knight'), ('exclusive', 'Exclusive Content of Gussy Bahi (Legacy)')], max_length=24),
        ),
    ]
