# Generated by Django 5.0.14 on 2026-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_tracking', '0012_saleevent_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved (awaiting wire)'), ('transferred', 'Transferred (wire sent)'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='transferred_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically when status is marked transferred / paid (admin wire sent).', null=True),
        ),
    ]
