# Generated by Django 5.0.14 on 2026-05-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_kingprogramselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanpurchase',
            name='currency',
            field=models.CharField(default='usd', max_length=8),
        ),
    ]
