# Generated by Django 5.2.13 on 2026-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_userplanpurchase_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboardentitlement',
            name='access_tier',
            field=models.CharField(choices=[('none', 'None'), ('money_mastery', 'Money Mastery'), ('king', 'The Knight'), ('full', 'Full access')], db_index=True, default='none', max_length=32),
        ),
    ]
