"""
Django settings for syndicate_backend project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path
from urllib.parse import quote_plus

from dotenv import dotenv_values, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _fill_empty_os_environ_from_dotenv(path: Path) -> None:
    """
    Copy variables from a .env file into os.environ only when the current value is empty.
    Fixes Windows/shell cases where OPENAI_API_KEY exists but is "" so load_dotenv(..., override=False)
    never applies the real key from backend/.env.
    """
    if not path.is_file():
        return
    for key, val in dotenv_values(path, encoding="utf-8-sig").items():
        if val is None:
            continue
        s = str(val).strip().strip("\ufeff")
        if not s:
            continue
        if not (os.environ.get(key) or "").strip():
            os.environ[key] = s


# Load .env from project root (handles UTF-8 BOM; also try cwd for alternate shells).
# override=False: real process env (e.g. Railway DATABASE_URL) must not be replaced by a stray .env.
for _env_path in (BASE_DIR / ".env", Path.cwd() / ".env"):
    if _env_path.is_file():
        load_dotenv(_env_path, override=False, encoding="utf-8-sig")
        break
else:
    load_dotenv(encoding="utf-8-sig")

# Always merge backend/.env into empty keys (see _fill_empty_os_environ_from_dotenv).
_fill_empty_os_environ_from_dotenv(BASE_DIR / ".env")


def _strip_optional_quotes(val: str) -> str:
    s = (val or "").strip().strip("\ufeff")
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        return s[1:-1].strip()
    return s


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-whr8w($+2y))zuz-azy2gr3897!ypihga1tzm$k06%m0&gaf-m")

# SECURITY WARNING: don't run with debug turned on in production!
_default_debug = "false" if (os.environ.get("RAILWAY_ENVIRONMENT") or "").strip() else "true"
DEBUG = os.environ.get("DJANGO_DEBUG", _default_debug).strip().lower() in ("1", "true", "yes")

_extra_hosts = [h.strip() for h in (os.environ.get("DJANGO_ALLOWED_HOSTS") or "").split(",") if h.strip()]
_allowed = ["localhost", "127.0.0.1", *_extra_hosts]
for _h in (os.environ.get("ALLOWED_HOSTS") or "").split(","):
    _h = _h.strip()
    if _h and _h not in _allowed:
        _allowed.append(_h)
_railway_host = (os.environ.get("RAILWAY_PUBLIC_DOMAIN") or "").strip()
if _railway_host and _railway_host not in _allowed:
    _allowed.append(_railway_host)
# In DEBUG, accept any Host (Next proxy, LAN IP, test client "testserver", etc.)
ALLOWED_HOSTS = ["*"] if DEBUG else _allowed

OPENAI_API_KEY = _strip_optional_quotes(os.environ.get("OPENAI_API_KEY") or "")
OPENAI_MODEL = _strip_optional_quotes(os.environ.get("OPENAI_MODEL") or "gpt-4o-mini")

USE_CLOUDINARY = bool(
    (os.environ.get("CLOUDINARY_URL") or "").strip()
    or (
        (os.environ.get("CLOUDINARY_CLOUD_NAME") or "").strip()
        and (os.environ.get("CLOUDINARY_API_KEY") or "").strip()
        and (os.environ.get("CLOUDINARY_API_SECRET") or "").strip()
    )
)


def _s3_object_storage_config() -> dict | None:
    """S3-*compatible* object storage: Railway Bucket, R2, Tigris, AWS S3, etc. (endpoint chooses the host)."""
    if (os.environ.get("USE_S3_OBJECT_STORAGE") or "").strip().lower() in ("0", "false", "no", "off"):
        return None
    # Railway Buckets: BUCKET, ACCESS_KEY_ID, SECRET_ACCESS_KEY, ENDPOINT, REGION (see railway.com/docs — Storage Buckets).
    # AWS SDK preset on Railway maps many of these to AWS_*; we accept both.
    railway_bucket = (os.environ.get("BUCKET") or "").strip()
    bucket = (
        (os.environ.get("AWS_STORAGE_BUCKET_NAME") or "").strip()
        or (os.environ.get("S3_BUCKET_NAME") or "").strip()
        or railway_bucket
    )
    access = (
        (os.environ.get("AWS_ACCESS_KEY_ID") or "").strip().strip("\ufeff")
        or (os.environ.get("ACCESS_KEY_ID") or "").strip().strip("\ufeff")
    )
    secret = (
        (os.environ.get("AWS_SECRET_ACCESS_KEY") or "").strip().strip("\ufeff")
        or (os.environ.get("SECRET_ACCESS_KEY") or "").strip().strip("\ufeff")
    )
    if not (bucket and access and secret):
        return None
    endpoint = (
        (os.environ.get("AWS_S3_ENDPOINT_URL") or "").strip()
        or (os.environ.get("S3_ENDPOINT_URL") or "").strip()
        or (os.environ.get("ENDPOINT") or "").strip()
    )
    if not endpoint:
        if access.startswith("tid_"):
            endpoint = "https://t3.storage.dev"
        elif railway_bucket and bucket == railway_bucket:
            # Bucket name came from Railway's BUCKET — use Railway's S3 API host.
            endpoint = "https://storage.railway.app"
    region = (
        (os.environ.get("AWS_S3_REGION_NAME") or "").strip()
        or (os.environ.get("AWS_DEFAULT_REGION") or "").strip()
        or (os.environ.get("REGION") or "").strip()
    )
    if not region:
        region = "auto" if access.startswith("tid_") else "us-east-1"
    return {
        "bucket_name": bucket,
        "access_key": access,
        "secret_key": secret,
        "endpoint_url": endpoint or None,
        "region_name": region,
    }


_s3_object_storage_cfg = _s3_object_storage_config()
USE_S3_OBJECT_STORAGE = _s3_object_storage_cfg is not None

# Source docs + uploads (place files here or upload via API)
SYNDICATE_DATA_DIR = BASE_DIR / "data"
SYNDICATE_MAX_DOC_CHARS = 120_000

# Admin/API multipart uploads.
# Default is set for large admin video uploads (15GB). Lower via DATA_UPLOAD_MAX_MB if desired.
_DATA_UPLOAD_MAX_MB = int((os.environ.get("DATA_UPLOAD_MAX_MB") or "15360").strip() or "15360")
DATA_UPLOAD_MAX_MEMORY_SIZE = max(2_621_440, _DATA_UPLOAD_MAX_MB * 1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE


# Application definition

_django_contrib = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS = []
if USE_CLOUDINARY:
    INSTALLED_APPS.append('cloudinary_storage')
INSTALLED_APPS.extend(_django_contrib)
if USE_CLOUDINARY:
    INSTALLED_APPS.append('cloudinary')
INSTALLED_APPS.extend(
    [
        'rest_framework',
        'rest_framework.authtoken',
        'corsheaders',
        'accounts.apps.AccountsConfig',
        'api',
        'apps.challenges.apps.ChallengesConfig',
        'apps.portal.apps.PortalConfig',
        'apps.membership.apps.MembershipConfig',
        'apps.affiliate_tracking.apps.AffiliateTrackingConfig',
        'apps.courses.apps.CoursesConfig',
        'apps.video_streaming.apps.VideoStreamingConfig',
        'apps.quiz_funnel.apps.QuizFunnelConfig',
    ]
)

# Optional: Redis for membership article search index (inverted index + short-lived result cache).
REDIS_URL = (os.environ.get("REDIS_URL") or "").strip()
# Celery (HLS transcoding worker). Broker defaults to REDIS_URL when CELERY_BROKER_URL is unset.
CELERY_BROKER_URL = (os.environ.get("CELERY_BROKER_URL") or "").strip() or (REDIS_URL or "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = (os.environ.get("CELERY_RESULT_BACKEND") or "").strip() or CELERY_BROKER_URL
CELERY_TASK_ALWAYS_EAGER = (os.environ.get("CELERY_TASK_ALWAYS_EAGER") or "").strip().lower() in (
    "1",
    "true",
    "yes",
)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_TIME_LIMIT = int((os.environ.get("CELERY_TASK_TIME_LIMIT") or "21600").strip() or "21600")
CELERY_TASK_SOFT_TIME_LIMIT = int((os.environ.get("CELERY_TASK_SOFT_TIME_LIMIT") or "21000").strip() or "21000")
CELERY_WORKER_PREFETCH_MULTIPLIER = int((os.environ.get("CELERY_WORKER_PREFETCH_MULTIPLIER") or "1").strip() or "1")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"


_mpr = (os.environ.get("MEMBERSHIP_ALLOW_ANONYMOUS_READ") or "").strip().lower()
if _mpr in ("0", "false", "no"):
    MEMBERSHIP_ALLOW_ANONYMOUS_READ = False
elif _mpr in ("1", "true", "yes"):
    MEMBERSHIP_ALLOW_ANONYMOUS_READ = True
else:
    MEMBERSHIP_ALLOW_ANONYMOUS_READ = DEBUG

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'syndicate_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'syndicate_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Local: SQLite (default). Production / Railway: set DATABASE_URL (Postgres plugin injects it),
# or set PGHOST + PGPORT + PGUSER + PGPASSWORD + PGDATABASE. Optional DATABASE_PUBLIC_URL
# is used if DATABASE_URL is empty (some templates expose only the public URL).


def _resolved_postgres_url() -> str | None:
    for key in ("DATABASE_URL", "DATABASE_PRIVATE_URL", "DATABASE_PUBLIC_URL"):
        v = (os.environ.get(key) or "").strip()
        if v:
            return v
    host = (os.environ.get("PGHOST") or "").strip()
    if not host:
        return None
    user = quote_plus((os.environ.get("PGUSER") or "").strip())
    password = quote_plus((os.environ.get("PGPASSWORD") or "").strip())
    database = (os.environ.get("PGDATABASE") or "").strip()
    port = (os.environ.get("PGPORT") or "5432").strip()
    if not database:
        return None
    return f"postgresql://{user}:{password}@{host}:{port}/{database}"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,
        },
    }
}

_pg_url = _resolved_postgres_url()
if _pg_url:
    import dj_database_url

    _ssl = (os.environ.get("DATABASE_SSL_REQUIRE") or "true").strip().lower() in (
        "1",
        "true",
        "yes",
    )
    DATABASES["default"] = dj_database_url.parse(
        _pg_url,
        conn_max_age=600,
        ssl_require=_ssl,
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
#
# Leading slash so /admin/ pages load CSS/JS from /static/... (not /admin/static/...).
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_ROOT.mkdir(parents=True, exist_ok=True)
# Explicit root for WhiteNoise (avoids edge cases where auto-detection disagrees with STATIC_ROOT).
WHITENOISE_ROOT = str(STATIC_ROOT)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Do not use WhiteNoise compressed/manifest storages: collectstatic post-processing fails on Railway.
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# django-storages/boto3 require these setting names; traffic goes to AWS_S3_ENDPOINT_URL
# (e.g. Railway Bucket https://storage.railway.app — not necessarily Amazon AWS).
if USE_S3_OBJECT_STORAGE and _s3_object_storage_cfg:
    AWS_ACCESS_KEY_ID = _s3_object_storage_cfg["access_key"]
    AWS_SECRET_ACCESS_KEY = _s3_object_storage_cfg["secret_key"]
    AWS_STORAGE_BUCKET_NAME = _s3_object_storage_cfg["bucket_name"]
    AWS_S3_REGION_NAME = _s3_object_storage_cfg["region_name"]
    if _s3_object_storage_cfg.get("endpoint_url"):
        AWS_S3_ENDPOINT_URL = _s3_object_storage_cfg["endpoint_url"]
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = True
    # Static/public media mode: set MEDIA_SIGNED_URLS=false to emit stable URLs that cache well.
    # Keep true for private buckets where presigned GET links are required.
    _media_signed_urls_raw = (os.environ.get("MEDIA_SIGNED_URLS") or "true").strip().lower()
    AWS_QUERYSTRING_AUTH = _media_signed_urls_raw in ("1", "true", "yes")
    _presign = int((os.environ.get("PRESIGNED_URL_EXPIRE_SECONDS") or "3600").strip() or "3600")
    AWS_QUERYSTRING_EXPIRE = max(60, min(_presign, 604800))
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
    }
elif USE_CLOUDINARY:
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Admin superuser (production): DJANGO_SUPERUSER_EMAIL / DJANGO_SUPERUSER_PASSWORD;
# Railway: `railway_start.sh` runs `manage.py ensure_superuser` after migrate.

_cors_env = (os.environ.get("CORS_ALLOWED_ORIGINS") or "").strip()
if _cors_env:
    CORS_ALLOWED_ORIGINS = [x.strip() for x in _cors_env.split(",") if x.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
_extra_cors = [o.strip() for o in (os.environ.get("CORS_EXTRA_ORIGINS") or "").split(",") if o.strip()]
if _extra_cors:
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys([*CORS_ALLOWED_ORIGINS, *_extra_cors]))

CORS_ALLOW_METHODS = ("DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT")

if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost(?::\d+)?$",
        r"^http://127\.0\.0\.1(?::\d+)?$",
    ]
else:
    CORS_ALLOWED_ORIGIN_REGEXES = []

if DEBUG and os.environ.get("CORS_ALLOW_ALL_IN_DEBUG", "true").lower() in ("1", "true", "yes"):
    CORS_ALLOW_ALL_ORIGINS = True

_csrf_env = (os.environ.get("CSRF_TRUSTED_ORIGINS") or "").strip()
if _csrf_env:
    CSRF_TRUSTED_ORIGINS = [x.strip() for x in _csrf_env.split(",") if x.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        *_extra_cors,
    ]

_rail_csrf = (os.environ.get("RAILWAY_PUBLIC_DOMAIN") or "").strip()
if _rail_csrf:
    _rail_origin = _rail_csrf if _rail_csrf.startswith("http") else f"https://{_rail_csrf}"
    _csrf_seen = {x.rstrip("/") for x in CSRF_TRUSTED_ORIGINS}
    if _rail_origin.rstrip("/") not in _csrf_seen:
        CSRF_TRUSTED_ORIGINS = [*CSRF_TRUSTED_ORIGINS, _rail_origin]
        _csrf_seen.add(_rail_origin.rstrip("/"))

_csrf_seen = {x.rstrip("/") for x in CSRF_TRUSTED_ORIGINS}
for _host in ALLOWED_HOSTS:
    if _host in ("localhost", "127.0.0.1", "*", ""):
        continue
    _origin = _host if "://" in _host else f"https://{_host}"
    _key = _origin.rstrip("/")
    if _key not in _csrf_seen:
        CSRF_TRUSTED_ORIGINS = [*CSRF_TRUSTED_ORIGINS, _origin]
        _csrf_seen.add(_key)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "EXCEPTION_HANDLER": "api.exception_handlers.drf_json_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Affiliate portal (OTP + tracking) — same env keys as legacy affiliate-portal/backend-django
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@syndicate.local")
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)
if EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend":
  EMAIL_BACKEND = "syndicate_backend.smtp_backend.RailwaySMTPEmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
# Normalize Gmail app-passwords pasted with spaces.
EMAIL_HOST_PASSWORD = (os.environ.get("EMAIL_HOST_PASSWORD", "") or "").replace(" ", "")
EMAIL_TIMEOUT = int((os.environ.get("EMAIL_TIMEOUT") or "15").strip() or "15")
_email_force_ipv4_raw = (os.environ.get("EMAIL_FORCE_IPV4") or "").strip().lower()
EMAIL_FORCE_IPV4 = _email_force_ipv4_raw in ("1", "true", "yes")
_email_use_ssl_raw = (os.environ.get("EMAIL_USE_SSL") or "").strip().lower()
EMAIL_USE_SSL = _email_use_ssl_raw in ("1", "true", "yes")
_email_use_tls_raw = os.environ.get("EMAIL_USE_TLS")
if _email_use_tls_raw is not None:
  EMAIL_USE_TLS = str(_email_use_tls_raw).strip().lower() in ("1", "true", "yes")
else:
  # Port 465 uses implicit TLS (SSL), not STARTTLS — default TLS off when SSL is on.
  EMAIL_USE_TLS = not EMAIL_USE_SSL
if EMAIL_USE_SSL and EMAIL_USE_TLS:
  EMAIL_USE_TLS = False
OTP_EXPIRES_MINUTES = int(os.environ.get("OTP_EXPIRES_MINUTES", "10"))
# Optional comma-separated Reply-To address(es). Use a discard-only mailbox (Hostinger filter:
# delete all incoming) so client "Reply" does not reach a monitored inbox. If unset, Reply-To is
# omitted and replies go to the From address (same as SMTP user for no-reply@).
OTP_MAIL_REPLY_TO = (os.environ.get("OTP_MAIL_REPLY_TO") or "").strip()
RESEND_API_KEY = (os.environ.get("RESEND_API_KEY") or "").strip()
RESEND_API_URL = (os.environ.get("RESEND_API_URL") or "https://api.resend.com/emails").strip()
EMAIL_FALLBACK_HOSTS = (os.environ.get("EMAIL_FALLBACK_HOSTS") or "").strip()
EMAIL_FALLBACK_PORTS = (os.environ.get("EMAIL_FALLBACK_PORTS") or "465,587").strip()
POST_LOGIN_REDIRECT_URL = os.environ.get("POST_LOGIN_REDIRECT_URL", "http://localhost:3000/")

# Stripe checkout (signup -> checkout -> dashboard).
FRONTEND_BASE_URL = (os.environ.get("FRONTEND_BASE_URL") or "http://localhost:3000").strip().rstrip("/")
MEDIA_PUBLIC_BASE_URL = (os.environ.get("MEDIA_PUBLIC_BASE_URL") or "").strip().rstrip("/")
STRIPE_SECRET_KEY = (os.environ.get("STRIPE_SECRET_KEY") or "").strip()
STRIPE_PUBLISHABLE_KEY = (os.environ.get("STRIPE_PUBLISHABLE_KEY") or "").strip()
# Backward compatibility: older env files used a typo `PCHECKOUT_AMOUNT_PENCE`.
_checkout_amount_raw = (
    (os.environ.get("CHECKOUT_AMOUNT_PENCE") or "").strip()
    or (os.environ.get("PCHECKOUT_AMOUNT_PENCE") or "").strip()
    or "33300"
)
try:
    CHECKOUT_AMOUNT_PENCE = int(_checkout_amount_raw)
except ValueError:
    CHECKOUT_AMOUNT_PENCE = 33300
if CHECKOUT_AMOUNT_PENCE < 50:
    CHECKOUT_AMOUNT_PENCE = 50
_pm_raw = (os.environ.get("STRIPE_CHECKOUT_PAYMENT_METHOD_TYPES") or "card,link").strip()
STRIPE_CHECKOUT_PAYMENT_METHOD_TYPES = tuple(
    x.strip() for x in _pm_raw.split(",") if x.strip()
) or ("card", "link")

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

if sys.version_info >= (3, 14):
    from copy import copy as _copy_context_dicts

    from django.template.context import BaseContext as _BaseContext

    def _base_context_copy(self):
        duplicate = _BaseContext()
        duplicate.__class__ = self.__class__
        duplicate.__dict__ = _copy_context_dicts(self.__dict__)
        duplicate.dicts = self.dicts[:]
        return duplicate

    _BaseContext.__copy__ = _base_context_copy

# Quieter runserver: optional Syndicate progress/streak calls hit 401 without a token — Django would log
# "Unauthorized: …" and a yellow 401 line for every poll. Skip those in DEBUG only.
if DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "filters": {
            "skip_http_401": {
                "()": "syndicate_backend.logging_filters.SkipHttp401Filter",
            },
        },
        "formatters": {
            "django.server": {
                "()": "django.utils.log.ServerFormatter",
                "format": "[{server_time}] {message}",
                "style": "{",
            },
        },
        "handlers": {
            "django_server_console": {
                "level": "INFO",
                "class": "logging.StreamHandler",
                "formatter": "django.server",
                "filters": ["skip_http_401"],
            },
            "django_request_console": {
                "level": "WARNING",
                "class": "logging.StreamHandler",
                "filters": ["skip_http_401"],
            },
        },
        "loggers": {
            "django.request": {
                "handlers": ["django_request_console"],
                "level": "WARNING",
                "propagate": False,
            },
            "django.server": {
                "handlers": ["django_server_console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }
