# Generated by Django 5.0.14 on 2026-09-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_funnel', '0002_quiz_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.DateTimeField(help_text='UTC start of the audit slot.')),
                ('slot_end', models.DateTimeField(help_text='UTC end of the audit slot.')),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=64)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('meet_link', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_bookings', to='quiz_funnel.user')),
            ],
            options={
                'db_table': 'quiz_audit_bookings',
                'ordering': ('-slot_start',),
                'indexes': [models.Index(fields=['user', 'status'], name='quiz_audit_user_status_idx'), models.Index(fields=['slot_start'], name='quiz_audit_slot_start_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='auditbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('user',), name='uniq_quiz_audit_one_booked_per_user'),
        ),
    ]
